# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# === Basic configuration ===

# Your application's name
appname: "HSSB::LockoutBoard"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# === Engines ===
#
# NOTE: All the engine configurations need to be under a single "engines:"
# key.  If you uncomment engine configurations below, make sure to delete
# all "engines:" lines except the first.  Otherwise, only the last
# "engines:" block will take effect.

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"

engines:
  template:
    template_toolkit:
      # Note: start_tag and end_tag are regexes
      start_tag: '<%'
      end_tag:   '%>'

plugins:
  Auth::Extensible:
    login_without_redirect: 1

    realms:
      users:
        provider: 'Database'
  Database:
    driver: SQLite
    database: 'data/boards.sqlite'
    on_connect_do:
      - 'create table if not exists boardobjectives ( board varchar(32) NOT NULL, objective_index integer not null, objective text not null, captured_by varchar(30), capture_utctime integer, primary key ( board, objective_index ))'
      - 'CREATE TABLE if not exists users ( id INTEGER AUTO_INCREMENT PRIMARY KEY, username VARCHAR(32) NOT NULL UNIQUE, password VARCHAR(40) NOT NULL)'
      - 'CREATE TABLE if not exists roles ( id INTEGER AUTO_INCREMENT PRIMARY KEY, role VARCHAR(32) NOT NULL)'
      - 'CREATE TABLE if not exists user_roles ( user_id INTEGER NOT NULL, role_id INTEGER NOT NULL, primary key (user_id, role_id))'
