apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  namespace: hssb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  resources:
    requests:
      storage: 5Gi
